# Generated by Django 2.2 on 2019-04-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0003_auto_20190416_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='product_type',
            field=models.CharField(blank=True, choices=[('MRK', 'Merkez'), ('FLL', 'filial')], max_length=25, null=True),
        ),
    ]
