# Generated by Django 2.2 on 2019-04-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0004_auto_20190416_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addmaterial.ProductType'),
        ),
    ]
