# Generated by Django 2.2 on 2019-04-17 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addmaterial', '0005_auto_20190416_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmaterial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addmaterial', to=settings.AUTH_USER_MODEL),
        ),
    ]
