# Generated by Django 2.2 on 2019-04-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0007_auto_20190417_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='product_typeadd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addmaterial', to='addmaterial.ProductType'),
        ),
    ]
