# Generated by Django 2.2.1 on 2019-05-05 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.IntegerField(blank=True, max_length=100, null=True)),
                ('received', models.IntegerField(blank=True, max_length=100, null=True)),
                ('used_type', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outmaterial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
