# Generated by Django 2.2 on 2019-04-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190414_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='product_type',
            field=models.CharField(blank=True, choices=[('MRK', 'Merkez'), ('FLL', 'filial')], max_length=25, null=True),
        ),
    ]
