# Generated by Django 2.2 on 2019-04-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190414_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddMaterial',
        ),
    ]
