# Generated by Django 2.2 on 2019-04-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_addmaterial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutMaterial',
        ),
    ]
