# Generated by Django 2.2.1 on 2019-05-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_outmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(blank=True, max_length=100, null=True)),
                ('yasadigi_region', models.CharField(blank=True, max_length=100, null=True)),
                ('profili', models.CharField(blank=True, max_length=100, null=True)),
                ('elaqenomresi', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('problemler', models.CharField(blank=True, max_length=100, null=True)),
                ('veziyyetsablonu', models.CharField(blank=True, max_length=100, null=True)),
                ('seher', models.CharField(blank=True, max_length=100, null=True)),
                ('kend', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AddMaterialProductType',
        ),
    ]
