# Generated by Django 2.2.1 on 2019-05-06 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190505_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutMaterial',
            new_name='Data',
        ),
    ]
