# Generated by Django 2.2.1 on 2019-05-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190505_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ad_soyad',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='elaqenomresi',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='kend',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='problemler',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='profili',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='seher',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='veziyyetsablonu',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='yasadigi_region',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
