# Generated by Django 2.2 on 2019-04-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, choices=[('MRK', 'Merkez'), ('FLL', 'filial')], max_length=25, null=True)),
                ('output_quality', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('received', models.CharField(max_length=100)),
                ('id_material', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
