# Generated by Django 2.2 on 2019-04-17 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addmaterial', '0008_auto_20190417_0400'),
        ('outmaterial', '0003_auto_20190416_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outmaterial',
            name='product_type',
        ),
        migrations.AddField(
            model_name='outmaterial',
            name='product_typeout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outmaterial', to='addmaterial.ProductType'),
        ),
    ]
