# Generated by Django 2.2 on 2019-04-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outmaterial', '0006_auto_20190422_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outmaterial',
            name='used_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
